return {
  BLOCK_SIZE = 50,
  BLOCK_LINE_COLOR ={236, 240, 241},
  COLLIDER_PADDING = 1,
  BACKGROUD_COLOR = {149, 165, 166},
  SHADOW_COLOR = {0,0,0,80},
  SHADOW_DISTANCE = 5,
  -- Controlles
  ROTATE_BLOCKGROUP_RIGHT = "e",
  ROTATE_BLOCKGROUP_LEFT = "q",
  DRAG_BLOCKGROUP = 1
}
